
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-api
  namespace: contacts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts-api
  template:
    metadata:
      labels:
        app: contacts-api
    spec:
      containers:
        - name: contacts-api
          image: kidsan/contacts-api:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: contacts-api