apiVersion: v1
kind: Service
metadata:
  name: contacts-api
  namespace: contacts
  labels:
    app: contacts-api
spec:
  selector:
    app: contacts-api
  ports:
    - port: 3000
      targetPort: 3000