apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-api
  namespace: contacts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts-api
  template:
    metadata:
      labels:
        app: contacts-api
        environment: prod